ew

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -22,9 +22,12 @@ jobs:
 
       - name: Download SDK
         run: |
-          wget --no-check-certificate \
-          "https://developer.garmin.com/downloads/connect-iq/${{ env.SDK_VERSION }}/connectiq-sdk-lin-${{ env.SDK_VERSION }}.zip" \
-          -O sdk.zip
+          # Tente a URL alternativa ou hospede o SDK localmente
+          DOWNLOAD_URL="https://developer.garmin.com/downloads/connect-iq/${{ env.SDK_VERSION }}/connectiq-sdk-lin-${{ env.SDK_VERSION }}.zip"
+          wget --no-check-certificate "$DOWNLOAD_URL" -O sdk.zip || {
+            echo "Download failed. Try checking: https://developer.garmin.com/connect-iq/"
+            exit 1
+          }
           unzip -q sdk.zip -d sdk
 
       - name: Generate developer key
